/*
 * SunRiZe
 * 
 * (c) 2017 by Marco Spreafico ( https://theing.blogspot.com )
 * 
 * This file is part of SunRiZe.
 *
 * SunRiZe is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SunRiZe is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#ifndef __StateDialogImplementation__
#define __StateDialogImplementation__

/**
@file
Subclass of StateDialog, which is generated by wxFormBuilder.
*/

#include "StateDialog.h"

//// end generated include

#include "Var.h"
#include "FieldsHelper.h"

/** Implementing StateDialog */
class StateDialogImplementation : public StateDialog
{
  private :
    FieldsHelper fields;
    Var var;
  
	protected:
		// Handlers for StateDialog events.
		void StateDialogOnInitDialog( wxInitDialogEvent& event );
	public:
		/** Constructor */
		StateDialogImplementation( wxWindow* parent , Var & v);
	//// end generated class members
	 Var & getVar();
};

#endif // __StateDialogImplementation__
